export const clinicInfo = {
  name: 'Clinique Pasteur Tunis',
  address: 'Centre Urbain Nord, 1003 Tunis, Tunisie',
  phone: '+216 36 402 000',
  urgences: '+216 36 402 076',
  email: 'contact@cliniquepasteur.com.tn',
  emailCommercial: 'commercial@cliniquepasteur.com.tn',
  horaires: '24h/24 - 7j/7',
  facebook: 'https://www.facebook.com/cliniquepasteurtunis',
  instagram: 'https://www.instagram.com/cliniquepasteurtunis',
  youtube: 'https://www.youtube.com/cliniquepasteurtunis',
  googleMaps: 'https://maps.google.com/?q=Clinique+Pasteur+Tunis+Centre+Urbain+Nord',
  stats: {
    specialites: 15,
    chambres: 79,
    blocsOperatoires: 10,
    niveaux: 11,
    litsReanimation: 21,
    cabinets: 30,
  }
};

export const chirurgies = [
  {
    slug: 'chirurgie-cardiovasculaire',
    title: 'Chirurgie Cardiovasculaire et Thoracique',
    shortTitle: 'Cardiovasculaire',
    icon: 'Heart',
    color: 'red',
    description: 'Prise en charge complète des pathologies cardiovasculaires avec une équipe chevronnée et des équipements de dernière technologie.',
    heroDescription: 'Le pôle cardiovasculaire de la Clinique Pasteur Tunis est reconnu comme l\'un des centres de référence en Tunisie pour la chirurgie cardiaque et vasculaire. Notre équipe pluridisciplinaire assure une prise en charge globale, du diagnostic au suivi post-opératoire.',
    prestations: [
      'Chirurgie cardiaque sous circulation extra-corporelle (CEC)',
      'Chirurgie cardiaque à cœur fermé',
      'Chirurgie cardiaque mini-invasive',
      'Chirurgie endovasculaire périphérique et aortique',
      'Pontage coronarien (PAC)',
      'Remplacement valvulaire (aortique, mitral)',
      'Réparation valvulaire',
      'Chirurgie de l\'aorte thoracique et abdominale',
      'Traitement des anévrismes',
      'Chirurgie des cardiopathies congénitales',
      'Pose de pacemaker et défibrillateur',
    ],
    equipements: [
      'Salle de cathétérisme cardiaque de dernière génération',
      'Bloc opératoire dédié avec CEC',
      'Unité de soins intensifs cardiologiques (USIC) - 8 lits',
      'Réanimation cardiologique - 11 lits',
      'Monitoring continu haute résolution',
      'Technologie NO (monoxyde d\'azote)',
      'Épuration extra-rénale sous toutes ses formes',
    ],
    avantages: [
      'Équipe chirurgicale de renommée nationale et internationale',
      'Réanimation post-chirurgie cardiaque dans une unité architecturalement séparée',
      'Prise en charge des adultes et des enfants (cardiopathies congénitales)',
      'Suivi post-opératoire personnalisé',
      'Taux de réussite parmi les meilleurs en Tunisie',
    ],
  },
  {
    slug: 'chirurgie-generale',
    title: 'Chirurgie Générale',
    shortTitle: 'Générale',
    icon: 'Stethoscope',
    color: 'blue',
    description: 'Interventions de chirurgie générale par voie classique et laparoscopique avec une expertise reconnue.',
    heroDescription: 'Le service de chirurgie générale de la Clinique Pasteur offre une prise en charge complète des pathologies abdominales et digestives. Nos chirurgiens maîtrisent les techniques les plus avancées, notamment la chirurgie laparoscopique mini-invasive.',
    prestations: [
      'Chirurgie digestive (estomac, intestin, côlon, rectum)',
      'Cholécystectomie (ablation vésicule biliaire)',
      'Appendicectomie',
      'Cure de hernie (inguinale, ombilicale, hiatale)',
      'Chirurgie du foie et des voies biliaires',
      'Chirurgie du pancréas',
      'Résections coliques',
      'Duodéno-pancréatectomie céphalique (DPC)',
      'Chirurgie des surrénales',
      'CHIP (Chimio-Hyperthermie Intrapéritonéale)',
      'Chirurgie thyroïdienne et parathyroïdienne',
    ],
    equipements: [
      'Blocs opératoires équipés des dernières technologies',
      'Colonnes de cœlioscopie HD',
      'Instruments de chirurgie mini-invasive',
      'Monitoring per-opératoire avancé',
    ],
    avantages: [
      'Expertise en chirurgie lourde digestive et urologique',
      'Maîtrise de la chirurgie laparoscopique',
      'Récupération rapide après chirurgie (RAAC)',
      'Équipe anesthésique dédiée',
    ],
  },
  {
    slug: 'chirurgie-orthopedique',
    title: 'Chirurgie Orthopédique',
    shortTitle: 'Orthopédique',
    icon: 'Bone',
    color: 'orange',
    description: 'Chirurgie de l\'appareil locomoteur : prothèses, arthroscopie, traumatologie, chirurgie du rachis.',
    heroDescription: 'Le service d\'orthopédie de la Clinique Pasteur prend en charge l\'ensemble des pathologies de l\'appareil locomoteur. De la traumatologie d\'urgence à la chirurgie prothétique programmée, notre équipe assure des soins de haute qualité.',
    prestations: [
      'Prothèse totale de hanche (PTH)',
      'Prothèse totale de genou (PTG)',
      'Prothèse d\'épaule',
      'Arthroscopie (genou, épaule, cheville)',
      'Chirurgie du rachis (hernie discale, scoliose)',
      'Chirurgie de la main et du poignet',
      'Chirurgie du pied',
      'Traumatologie (fractures, luxations)',
      'Ligamentoplastie du genou (LCA)',
      'Chirurgie des tendons (coiffe des rotateurs)',
      'Ostéosynthèse',
    ],
    equipements: [
      'Arthroscope haute définition',
      'Amplificateur de brillance',
      'Motor system pour chirurgie osseuse',
      'Matériel d\'ostéosynthèse complet',
    ],
    avantages: [
      'Techniques mini-invasives privilégiées',
      'Rééducation précoce post-opératoire',
      'Prise en charge des urgences traumatologiques 24h/24',
      'Suivi personnalisé à long terme',
    ],
  },
  {
    slug: 'chirurgie-bariatrique',
    title: 'Chirurgie Bariatrique',
    shortTitle: 'Bariatrique',
    icon: 'Scale',
    color: 'purple',
    description: 'Centre de référence en chirurgie de l\'obésité : sleeve, bypass, anneau gastrique.',
    heroDescription: 'La chirurgie bariatrique a fait, en partie, la réputation de la Clinique Pasteur Tunis. Notre centre de chirurgie de l\'obésité représente une part importante de l\'activité chirurgicale de l\'établissement, avec des résultats reconnus au niveau national et international.',
    prestations: [
      'Sleeve gastrectomie (gastrectomie en manchon)',
      'Bypass gastrique (Roux-en-Y)',
      'Mini bypass gastrique',
      'Anneau gastrique ajustable',
      'Chirurgie de révision bariatrique',
      'Ballon intragastrique',
      'Bilan pré-opératoire complet',
      'Suivi nutritionnel pré et post-opératoire',
      'Accompagnement psychologique',
      'Chirurgie réparatrice post-amaigrissement (abdominoplastie)',
    ],
    equipements: [
      'Bloc opératoire dédié à la cœlioscopie',
      'Instruments bariatriques spécialisés',
      'Matériel de suture mécanique de dernière génération',
      'Monitoring per-opératoire spécifique',
    ],
    avantages: [
      'Centre de référence avec un volume d\'activité important',
      'Approche multidisciplinaire (chirurgien, nutritionniste, psychologue)',
      'Chirurgie 100% laparoscopique (mini-invasive)',
      'Programme de suivi à long terme',
      'Coaching nutritionnel intégré à la clinique',
      'Prise en charge des patients internationaux',
    ],
  },
  {
    slug: 'chirurgie-esthetique',
    title: 'Chirurgie Esthétique et Réparatrice',
    shortTitle: 'Esthétique',
    icon: 'Sparkles',
    color: 'pink',
    description: 'Chirurgie esthétique du visage et du corps : liposuccion, rhinoplastie, lifting, augmentation mammaire.',
    heroDescription: 'Le centre de chirurgie esthétique et réparatrice de la Clinique Pasteur Tunis offre des prestations de haute qualité dans un environnement médical sécurisé. Nos chirurgiens plasticiens allient expertise technique et sens artistique.',
    prestations: [
      'Rhinoplastie (chirurgie du nez)',
      'Lifting cervico-facial',
      'Blépharoplastie (chirurgie des paupières)',
      'Otoplastie (chirurgie des oreilles)',
      'Augmentation mammaire (prothèses)',
      'Réduction mammaire',
      'Lifting des seins (mastopexie)',
      'Abdominoplastie',
      'Liposuccion / Lipoaspiration',
      'Lipofilling (injection de graisse)',
      'Body contouring post-amaigrissement',
      'Chirurgie intime',
      'Greffe de cheveux',
      'Injections (acide hyaluronique, botox)',
    ],
    equipements: [
      'Bloc opératoire aux normes internationales',
      'Canules de liposuccion dernière génération',
      'Matériel d\'injection haute précision',
      'Chambres VIP pour convalescence',
    ],
    avantages: [
      'Chirurgiens plasticiens certifiés et expérimentés',
      'Consultation personnalisée avec simulation',
      'Cadre médical sécurisé (bloc opératoire, réanimation)',
      'Chambres suites et VIP pour le confort post-opératoire',
      'Tarifs compétitifs par rapport à l\'Europe',
      'Prise en charge des patients internationaux',
    ],
  },
  {
    slug: 'chirurgie-urologique',
    title: 'Chirurgie Urologique',
    shortTitle: 'Urologique',
    icon: 'Activity',
    color: 'teal',
    description: 'Prise en charge des pathologies urologiques par voie classique et laparoscopique.',
    heroDescription: 'Le service d\'urologie de la Clinique Pasteur assure le diagnostic et le traitement chirurgical de l\'ensemble des pathologies de l\'appareil urinaire et génital masculin, avec une expertise particulière en chirurgie laparoscopique.',
    prestations: [
      'Prostatectomie radicale (cancer de la prostate)',
      'Résection transurétrale de la prostate (RTUP)',
      'Néphrectomie (ablation du rein)',
      'Chirurgie des calculs rénaux (lithotritie)',
      'Urétéroscopie',
      'Cystectomie (cancer de la vessie)',
      'Chirurgie de l\'incontinence urinaire',
      'Chirurgie des malformations urogénitales',
      'Circumcision',
      'Varicocèle',
      'Chirurgie de la surrénale par voie laparoscopique',
    ],
    equipements: [
      'Urétéroscope souple et rigide',
      'Laser pour lithotritie',
      'Résecteur bipolaire',
      'Colonne de cœlioscopie dédiée',
    ],
    avantages: [
      'Expertise en chirurgie lourde urologique',
      'Chirurgie laparoscopique privilégiée',
      'Centre d\'explorations urodynamiques intégré',
      'Prise en charge multidisciplinaire des cancers urologiques',
    ],
  },
  {
    slug: 'chirurgie-orl',
    title: 'Chirurgie ORL',
    shortTitle: 'ORL',
    icon: 'Ear',
    color: 'indigo',
    description: 'Chirurgie oto-rhino-laryngologique : nez, gorge, oreilles, glandes salivaires.',
    heroDescription: 'Le service ORL de la Clinique Pasteur prend en charge les pathologies du nez, de la gorge, des oreilles et du cou. Nos spécialistes ORL utilisent les techniques chirurgicales les plus modernes pour des résultats optimaux.',
    prestations: [
      'Amygdalectomie et adénoïdectomie',
      'Chirurgie des sinus (sinusite chronique)',
      'Septoplastie (déviation de la cloison nasale)',
      'Tympanoplastie (chirurgie du tympan)',
      'Chirurgie de l\'otite chronique',
      'Chirurgie des glandes salivaires',
      'Thyroïdectomie',
      'Chirurgie des cordes vocales',
      'Chirurgie des tumeurs cervicales',
      'Pose d\'aérateurs transtympaniques (drains)',
      'Chirurgie endoscopique naso-sinusienne',
    ],
    equipements: [
      'Microscope opératoire',
      'Endoscope ORL haute définition',
      'Instruments de microchirurgie',
      'Monitoring du nerf facial',
    ],
    avantages: [
      'Techniques endoscopiques mini-invasives',
      'Chirurgie ambulatoire possible',
      'Prise en charge pédiatrique',
      'Expertise en chirurgie cervicale',
    ],
  },
  {
    slug: 'neurochirurgie',
    title: 'Neurochirurgie',
    shortTitle: 'Neurochirurgie',
    icon: 'Brain',
    color: 'violet',
    description: 'Chirurgie du cerveau, de la moelle épinière et des nerfs périphériques.',
    heroDescription: 'Le service de neurochirurgie de la Clinique Pasteur Tunis prend en charge les pathologies du système nerveux central et périphérique. Notre équipe neurochirurgicale bénéficie d\'un plateau technique de pointe.',
    prestations: [
      'Chirurgie des tumeurs cérébrales',
      'Chirurgie de la hernie discale cervicale et lombaire',
      'Chirurgie du canal lombaire étroit',
      'Chirurgie du rachis (stabilisation, arthrodèse)',
      'Chirurgie des hématomes intracrâniens',
      'Traitement chirurgical de l\'épilepsie',
      'Chirurgie des malformations vasculaires cérébrales',
      'Neuronavigation',
      'Chirurgie des nerfs périphériques',
      'Traitement de la névralgie du trijumeau',
    ],
    equipements: [
      'Microscope opératoire neurochirurgical',
      'Système de neuronavigation',
      'Monitoring neurophysiologique per-opératoire',
      'IRM pré-opératoire de haute résolution',
    ],
    avantages: [
      'Équipe neurochirurgicale expérimentée',
      'Réanimation polyvalente dédiée (10 lits)',
      'Imagerie de pointe (IRM, Scanner)',
      'Collaboration avec le centre d\'explorations neurophysiologiques',
    ],
  },
  {
    slug: 'chirurgie-pediatrique',
    title: 'Chirurgie Pédiatrique',
    shortTitle: 'Pédiatrique',
    icon: 'Baby',
    color: 'cyan',
    description: 'Chirurgie adaptée aux enfants : malformations, hernies, appendicite, pathologies urologiques.',
    heroDescription: 'Le service de chirurgie pédiatrique de la Clinique Pasteur offre une prise en charge chirurgicale spécialisée pour les nouveau-nés, nourrissons, enfants et adolescents, dans un environnement rassurant et adapté.',
    prestations: [
      'Chirurgie des hernies inguinales de l\'enfant',
      'Appendicectomie pédiatrique',
      'Chirurgie des malformations congénitales',
      'Chirurgie urologique pédiatrique (hypospadias, cryptorchidie)',
      'Circoncision',
      'Chirurgie des malformations digestives',
      'Chirurgie des cardiopathies congénitales',
      'Chirurgie ORL pédiatrique',
      'Traumatologie pédiatrique',
    ],
    equipements: [
      'Matériel chirurgical adapté à la pédiatrie',
      'Monitoring pédiatrique spécialisé',
      'Anesthésie pédiatrique dédiée',
    ],
    avantages: [
      'Chirurgiens spécialisés en pédiatrie',
      'Anesthésistes pédiatriques',
      'Environnement adapté aux enfants',
      'Présence parentale facilitée',
    ],
  },
  {
    slug: 'chirurgie-endoscopique',
    title: 'Chirurgie Endoscopique',
    shortTitle: 'Endoscopique',
    icon: 'Scan',
    color: 'emerald',
    description: 'Interventions mini-invasives par voie endoscopique pour un rétablissement rapide.',
    heroDescription: 'La chirurgie endoscopique permet de réaliser des interventions complexes avec un minimum d\'incisions, réduisant la douleur post-opératoire et accélérant la récupération. La Clinique Pasteur dispose d\'un plateau technique complet pour cette spécialité.',
    prestations: [
      'Endoscopie digestive haute et basse',
      'Cholécystectomie par voie endoscopique',
      'Chirurgie colorectale endoscopique',
      'CPRE (Cholangio-Pancréatographie Rétrograde Endoscopique)',
      'Sphinctérotomie endoscopique',
      'Polypectomie',
      'Mucosectomie',
      'Dilatation endoscopique',
      'Pose de prothèses digestives',
    ],
    equipements: [
      'Colonnes d\'endoscopie haute définition',
      'Vidéo-endoscopes de dernière génération',
      'Matériel de résection endoscopique',
      'Salle d\'endoscopie dédiée',
    ],
    avantages: [
      'Cicatrices minimales',
      'Durée d\'hospitalisation réduite',
      'Récupération rapide',
      'Moins de douleur post-opératoire',
    ],
  },
  {
    slug: 'chirurgie-coelioscopique',
    title: 'Chirurgie Cœlioscopique',
    shortTitle: 'Cœlioscopique',
    icon: 'Monitor',
    color: 'lime',
    description: 'Chirurgie laparoscopique mini-invasive pour les interventions abdominales et pelviennes.',
    heroDescription: 'La chirurgie cœlioscopique (ou laparoscopique) est une technique mini-invasive qui permet de réaliser des opérations abdominales à travers de petites incisions. La Clinique Pasteur est pionnière dans cette approche en Tunisie.',
    prestations: [
      'Cholécystectomie cœlioscopique',
      'Appendicectomie cœlioscopique',
      'Cure de hernie par cœlioscopie',
      'Chirurgie colorectale laparoscopique',
      'Sleeve gastrectomie',
      'Bypass gastrique',
      'Surrénalectomie laparoscopique',
      'Prostatectomie laparoscopique',
      'Néphrectomie laparoscopique',
      'Hystérectomie cœlioscopique',
    ],
    equipements: [
      'Colonnes de cœlioscopie HD dernière génération',
      'Instruments de dissection et coagulation avancés',
      'Trocarts spécialisés',
      'Système d\'insufflation CO2 régulé',
    ],
    avantages: [
      'Cicatrices quasi-invisibles',
      'Hospitalisation courte (1-3 jours)',
      'Reprise d\'activité rapide',
      'Moins de complications post-opératoires',
    ],
  },
  {
    slug: 'chirurgie-carcinologique',
    title: 'Chirurgie Carcinologique',
    shortTitle: 'Carcinologique',
    icon: 'Shield',
    color: 'amber',
    description: 'Chirurgie des cancers : digestifs, urologiques, gynécologiques, thyroïdiens.',
    heroDescription: 'Le service de chirurgie carcinologique de la Clinique Pasteur assure la prise en charge chirurgicale des tumeurs malignes. Notre approche multidisciplinaire garantit un traitement optimal, adapté à chaque patient.',
    prestations: [
      'Chirurgie des cancers digestifs (estomac, côlon, rectum, foie)',
      'Chirurgie des cancers urologiques (rein, vessie, prostate)',
      'Chirurgie des cancers gynécologiques',
      'Chirurgie des cancers thyroïdiens',
      'Chirurgie des cancers du sein',
      'CHIP (Chimio-Hyperthermie Intrapéritonéale)',
      'Curage ganglionnaire',
      'Chirurgie de reconstruction post-cancer',
      'Biopsies chirurgicales',
    ],
    equipements: [
      'Bloc opératoire avec matériel spécialisé',
      'Laboratoire d\'analyses intégré pour examens extemporanés',
      'Imagerie complète (IRM, Scanner, Échographie)',
    ],
    avantages: [
      'Approche multidisciplinaire (chirurgien, oncologue, radiologue)',
      'Techniques mini-invasives quand possible',
      'Accompagnement psychologique du patient',
      'Suivi post-opératoire rigoureux',
    ],
  },
  {
    slug: 'chirurgie-gyneco-obstetrique',
    title: 'Chirurgie Gynéco-Obstétrique',
    shortTitle: 'Gynéco-Obstétrique',
    icon: 'HeartPulse',
    color: 'rose',
    description: 'Obstétrique, gynécologie chirurgicale et accouchement dans un cadre sécurisé.',
    heroDescription: 'Le service de gynécologie-obstétrique de la Clinique Pasteur offre une prise en charge complète de la femme, de la grossesse à la ménopause. Notre maternité dispose de deux box d\'accouchement et d\'une salle de césarienne dédiée.',
    prestations: [
      'Accouchement naturel assisté',
      'Césarienne programmée et en urgence',
      'Hystérectomie (voie haute, basse, cœlioscopique)',
      'Myomectomie (fibromes utérins)',
      'Chirurgie de l\'endométriose',
      'Chirurgie de l\'infertilité',
      'Cure de prolapsus',
      'Chirurgie ovarienne (kyste, tumeur)',
      'Curetage',
      'Conisation du col utérin',
      'Chirurgie du sein (tumeurs bénignes et malignes)',
    ],
    equipements: [
      '2 box d\'accouchement mitoyens à une salle de césarienne',
      '9 chambres d\'hospitalisation dédiées (7 standard + 2 VIP)',
      'Monitoring fœtal continu',
      'Colonne de cœlioscopie gynécologique',
      'Échographe obstétrical',
    ],
    avantages: [
      'Maternité sécurisée avec bloc opératoire adjacent',
      'Équipe obstétricale disponible 24h/24',
      'Chambres VIP pour un séjour confortable',
      'Prise en charge néonatale immédiate si nécessaire',
    ],
  },
  {
    slug: 'electrophysiologie',
    title: 'Électrophysiologie Cardiaque',
    shortTitle: 'Électrophysiologie',
    icon: 'Zap',
    color: 'yellow',
    description: 'Diagnostic et traitement des troubles du rythme cardiaque par des techniques de pointe.',
    heroDescription: 'L\'unité d\'électrophysiologie de la Clinique Pasteur dispose d\'une salle totalement équipée et dédiée au diagnostic et au traitement des troubles du rythme cardiaque. C\'est l\'un des centres de référence en Tunisie pour la rythmologie.',
    prestations: [
      'Exploration électrophysiologique endocavitaire',
      'Ablation par radiofréquence des arythmies',
      'Ablation de la fibrillation auriculaire',
      'Ablation du flutter auriculaire',
      'Ablation des tachycardies ventriculaires',
      'Implantation de pacemaker',
      'Implantation de défibrillateur automatique (DAI)',
      'Resynchronisation cardiaque (CRT)',
      'Holter ECG et tensionnel',
      'Test d\'effort',
    ],
    equipements: [
      'Salle d\'électrophysiologie totalement équipée et dédiée',
      'Système de cartographie 3D des arythmies',
      'Cathéters d\'ablation dernière génération',
      'Monitoring en temps réel',
    ],
    avantages: [
      'Salle entièrement dédiée à la rythmologie',
      'Équipe spécialisée en électrophysiologie',
      'Techniques d\'ablation de dernière génération',
      'Suivi post-implantation rigoureux',
    ],
  },
];

export const centres = [
  {
    slug: 'urgences',
    title: 'Service des Urgences',
    shortTitle: 'Urgences',
    icon: 'Siren',
    color: 'red',
    description: 'Urgences médicales et chirurgicales 24h/24, 7j/7 avec une équipe médicale dédiée.',
    fullDescription: 'Le service des urgences de la Clinique Pasteur est opérationnel 24 heures sur 24, 7 jours sur 7. Une équipe médicale et paramédicale qualifiée assure la prise en charge immédiate de toutes les urgences médicales et chirurgicales. Le service est directement connecté aux blocs opératoires et aux unités de réanimation pour une prise en charge optimale des cas critiques.',
    services: [
      'Accueil et tri des urgences',
      'Urgences médicales (cardiologiques, neurologiques, respiratoires)',
      'Urgences chirurgicales (traumatologie, chirurgie digestive)',
      'Urgences gynéco-obstétriques',
      'Urgences pédiatriques',
      'Réanimation d\'urgence',
      'Imagerie d\'urgence (Scanner, Radiologie)',
      'Biologie d\'urgence',
    ],
  },
  {
    slug: 'explorations-cardiaques',
    title: 'Centre d\'Explorations Cardiaques',
    shortTitle: 'Explorations Cardiaques',
    icon: 'HeartPulse',
    color: 'red',
    description: 'Explorations cardiaques non invasives et invasives avec équipement de dernière technologie.',
    fullDescription: 'Le centre d\'explorations cardiaques regroupe l\'ensemble des examens diagnostiques du cœur et des vaisseaux. Toutes les explorations non invasives sont regroupées dans un service autonome, offrant une prise en charge rapide et efficace.',
    services: [
      'Échocardiographie transthoracique (ETT)',
      'Échocardiographie transœsophagienne (ETO)',
      'Échocardiographie de stress',
      'Électrocardiogramme (ECG)',
      'Holter ECG (24h-48h)',
      'Holter tensionnel (MAPA)',
      'Épreuve d\'effort sur tapis roulant',
      'Coronarographie diagnostique',
      'Cathétérisme cardiaque droit et gauche',
      'Angioplastie coronaire',
      'Valvuloplastie percutanée',
    ],
  },
  {
    slug: 'explorations-neurophysiologiques',
    title: 'Centre d\'Explorations Neurophysiologiques',
    shortTitle: 'Explorations Neurophysiologiques',
    icon: 'Brain',
    color: 'purple',
    description: 'Diagnostic des pathologies neurologiques par explorations fonctionnelles.',
    fullDescription: 'Le centre d\'explorations neurophysiologiques réalise l\'ensemble des examens fonctionnels du système nerveux, permettant le diagnostic précis des pathologies neurologiques et neuromusculaires.',
    services: [
      'Électroencéphalogramme (EEG)',
      'Électromyogramme (EMG)',
      'Potentiels évoqués (visuels, auditifs, somesthésiques)',
      'Vidéo-EEG prolongé',
      'Bilan pré-chirurgical de l\'épilepsie',
      'Étude des vitesses de conduction nerveuse',
    ],
  },
  {
    slug: 'laboratoire',
    title: 'Laboratoire d\'Analyses Médicales',
    shortTitle: 'Laboratoire',
    icon: 'FlaskConical',
    color: 'blue',
    description: 'Analyses biologiques complètes avec résultats rapides pour un diagnostic précis.',
    fullDescription: 'Le laboratoire d\'analyses médicales de la Clinique Pasteur réalise l\'ensemble des examens biologiques nécessaires au diagnostic et au suivi des patients, avec des délais de rendu optimisés.',
    services: [
      'Biochimie',
      'Hématologie',
      'Hémostase',
      'Bactériologie',
      'Sérologie et immunologie',
      'Marqueurs tumoraux',
      'Biologie d\'urgence 24h/24',
      'Bilan pré-opératoire complet',
      'Analyses de routine et spécialisées',
    ],
  },
  {
    slug: 'endoscopie',
    title: 'Centre d\'Endoscopie',
    shortTitle: 'Endoscopie',
    icon: 'Scan',
    color: 'green',
    description: 'Explorations endoscopiques digestives diagnostiques et thérapeutiques.',
    fullDescription: 'Le centre d\'endoscopie de la Clinique Pasteur est équipé de vidéo-endoscopes de dernière génération pour réaliser l\'ensemble des explorations endoscopiques digestives, tant diagnostiques que thérapeutiques.',
    services: [
      'Fibroscopie gastrique (FOGD)',
      'Coloscopie',
      'Écho-endoscopie',
      'CPRE (Cholangio-Pancréatographie Rétrograde Endoscopique)',
      'Polypectomie endoscopique',
      'Mucosectomie',
      'Pose de prothèses digestives',
      'Dilatation endoscopique',
      'Ligature de varices œsophagiennes',
    ],
  },
  {
    slug: 'explorations-urodynamiques',
    title: 'Centre d\'Explorations Urodynamiques',
    shortTitle: 'Explorations Urodynamiques',
    icon: 'Activity',
    color: 'teal',
    description: 'Bilan urodynamique complet pour le diagnostic des troubles urinaires.',
    fullDescription: 'Le centre d\'explorations urodynamiques réalise des bilans complets pour diagnostiquer les troubles fonctionnels de l\'appareil urinaire. Ces examens sont essentiels avant toute intervention chirurgicale urologique.',
    services: [
      'Débitmétrie',
      'Cystomanométrie',
      'Profil de pression urétrale',
      'Bilan urodynamique complet',
      'Échographie vésico-rénale',
      'Étude pression-débit',
    ],
  },
  {
    slug: 'radiologie',
    title: 'Centre de Radiologie',
    shortTitle: 'Radiologie',
    icon: 'ScanLine',
    color: 'indigo',
    description: 'Plateau technique de pointe : IRM, scanner double énergie, mammographie.',
    fullDescription: 'Le centre de radiologie de la Clinique Pasteur dispose d\'un plateau technique extrêmement performant. Une équipe de médecins radiologues spécialisés assure l\'ensemble des examens d\'imagerie conventionnelle et interventionnelle.',
    services: [
      'IRM (Imagerie par Résonance Magnétique)',
      'Scanner double énergie',
      'Radiologie conventionnelle (table télécommandée)',
      'Radiologie osseuse (tables Os poumons dont une à capteur plan)',
      'Mammographie',
      'Panoramique dentaire 2D',
      'Ostéodensitométrie',
      'Échographie générale et spécialisée',
      'Radiologie interventionnelle (embolisation, drainage, radiofréquence)',
    ],
  },
  {
    slug: 'hospitalisation-jour',
    title: 'Hospitalisation de Jour',
    shortTitle: 'Hôpital du Jour',
    icon: 'Clock',
    color: 'orange',
    description: 'Prise en charge ambulatoire pour des actes ne nécessitant pas d\'hospitalisation prolongée.',
    fullDescription: 'Le service d\'hospitalisation de jour permet la réalisation d\'actes médicaux et chirurgicaux ambulatoires. Le patient est admis le matin et peut rentrer chez lui le jour même, dans un cadre confortable et sécurisé.',
    services: [
      'Chirurgie ambulatoire',
      'Endoscopies digestives',
      'Explorations cardiaques',
      'Chimiothérapie',
      'Perfusions et traitements IV',
      'Biopsies',
      'Bilans de santé complets',
      'Soins post-opératoires de suivi',
    ],
  },
  {
    slug: 'coaching-nutritionnel-esthetique',
    title: 'Coaching Nutritionnel & Centre Esthétique',
    shortTitle: 'Nutrition & Esthétique',
    icon: 'Apple',
    color: 'lime',
    description: 'Accompagnement nutritionnel personnalisé et soins esthétiques non chirurgicaux.',
    fullDescription: 'Le centre de coaching nutritionnel et esthétique de la Clinique Pasteur offre un accompagnement personnalisé pour la gestion du poids, la nutrition thérapeutique et les soins esthétiques non chirurgicaux.',
    services: [
      'Bilan nutritionnel complet',
      'Programme de perte de poids personnalisé',
      'Suivi nutritionnel pré et post chirurgie bariatrique',
      'Nutrition thérapeutique (diabète, insuffisance rénale, etc.)',
      'Soins esthétiques du visage',
      'Soins esthétiques du corps',
      'Médecine esthétique (injections, peelings)',
      'Programmes bien-être',
    ],
  },
];

export const niveaux = [
  {
    etage: '7ème et 6ème étage',
    titre: 'Blocs Opératoires & Réanimation',
    description: '10 salles d\'opération dont une septique, 11 lits de réanimation cardiologique, 10 lits de réanimation polyvalente, stérilisation centrale informatisée avec traçabilité complète.',
    details: ['10 salles d\'opération', '11 lits réanimation cardiologique', '10 lits réanimation polyvalente', 'Stérilisation centrale informatisée'],
  },
  {
    etage: '5ème étage',
    titre: 'Cathétérisme & Soins Intensifs',
    description: 'Salle de cathétérisme cardiaque, 7 chambres de soins intensifs (1 suite + 1 confort + 5 standard), 8 lits d\'USIC avec matériel de pointe.',
    details: ['1 salle de cathétérisme', '7 chambres soins intensifs', '8 lits USIC', 'Matériel haute technologie'],
  },
  {
    etage: '4ème au 1er étage + Hôpital du Jour',
    titre: 'Hospitalisation',
    description: '79 chambres réparties en chambres individuelles, confort et suites VIP pour un séjour adapté à chaque patient.',
    details: ['68 chambres individuelles', '8 chambres confort', '6 chambres suites / VIP', '3 chambres hospitalisation du jour'],
  },
  {
    etage: 'Mezzanine',
    titre: 'Maternité',
    description: '2 box d\'accouchement mitoyens à une salle de césarienne, 9 chambres d\'hospitalisation dont 2 VIP.',
    details: ['2 box d\'accouchement', '1 salle de césarienne', '7 chambres standard', '2 chambres VIP'],
  },
  {
    etage: 'RDC',
    titre: 'Accueil & Consultations',
    description: 'Accueil des patients, urgences, consultations externes, explorations.',
    details: ['Accueil central', 'Service des urgences', 'Consultations', 'Centre médical (30 cabinets)'],
  },
  {
    etage: 'Sous-sols',
    titre: 'Plateau Technique',
    description: 'Centre de radiologie (IRM, Scanner, Mammographie), laboratoire d\'analyses, services techniques.',
    details: ['IRM', 'Scanner double énergie', 'Mammographie', 'Laboratoire d\'analyses'],
  },
];
